language: cpp
sudo: required
dist: trusty
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        - llvm-toolchain-precise
        packages:
        - gcc-5
        - g++-5
  - os: osx
    compiler: clang
before_install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
before_script: 
script:
- make
- make test
- make release
after_success: 
notifications:
  email: false
before_deploy:
- export RELEASE_PKG_FILE=$(ls build/*.zip)
- echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: kKnsr4zVEtM6a04CUlNe9WjvInsAdFeOzfO/9igSAyjXXTSKldWsHBjXZ7iXWyVu7/9rcxn6Btxnf3b1CaUFnntepB4VPHSdRKnonvWk5l7TIRkDL/PChpuptnBWH5dTYAjEasr0pSHSH/iEz0G39KtjSLL7OamstM4MAEl5q0ZZNnLNA9qpn7CTnpT8xTXSkKYLM7iRy1RxEITV9LfnPWENC5G5GC4b2eLR1F9OnCTRja9WrIVOD48uDEf72lsii8RkzcStBtx/5pnHB7jTc8sURYWox5qsslL8JD4hqjik9Lt/fKiJ+ON80QSFPcOSedlsG95GLb0x11lH5Rkt/KtT9b2Osv54nBLb848AbnuT4fLMwpTfCdqgpMv5QlAHQFKY9mHPK9nTFZ7hSc/udEJZQ2N9YGibpkv7h5v0Hw+e3daXcLSVLckq+TEKtujJkvisSKWPD4goYOykpCsqwUWiNvq1vSAN7or6pPBHh73v8eteMZclLMUBa9S8OoroPzd8O++uwIyiDs5o+5ILwuvqxbOcHYcVUPyb5DRKeOCYKmdBuIj9pOBwwJZJuYuMpbr++3geTcER3buuTvBSG9RdPwYrc7CInI9/o4JQ0Gxv+frfgFUY864PTCssDGj/7BuKNY7Y/FkjpZp3v0Aj0PjvM0s1/AXN9Sp2CO34CfA=
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  on:
    repo: peposso/xlsx2lua
    tags: true
  skip_cleanup: true
