language: cpp
sudo: required
dist: trusty
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        - llvm-toolchain-precise
        packages:
        - gcc-5
        - g++-5
  - os: osx
    compiler: clang
before_install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
before_script: 
script:
- make
- make test
- make release
after_success: 
notifications:
  email: false
before_deploy:
- export RELEASE_PKG_FILE=$(ls build/*.zip)
- echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: "Z6qnIGq/IxqDEGOjFokswPZhpn5vtVFckTWFgHdWfu1JHeJALs+EG35/BanZp0MGecSLnv5HRV7ZbI1lWh+UDQQ/6hPLjs0AL1mBLuTXB8TIm1mdVKHZEzGxXfLMxO7fCIvPlyutUX6hsjBE976IUvoq7QMOyD1iG/AxcwVh1Tumiut/LVJ/rdYPUWoZ+ZOgV7TXK4o0aOQT1D71eMMiXXEW42vxW76zXetDaZ4a/IDNW90IeOH3U5mEo3kVayzyG5r92v9SSW/umaDAyvJhubHRNBUXyh4v5hz/PqPJjWZODre6UemfMewqN4vm75HsjURna3+lDJfPQDC8Tc1DV2b8J0urMUN0XMt9HZMzq2xol+L40JqdQH7ul9CMs0otMaGHudgigV1mBa79yRQixyR04ngcEgA+w7oaBwRrV//F/Nktxoj7Mm/6SJIwPZaG+CQf5WQxtdWPnXQO38FYoxdtcYRJdoBqBU3JqMIZUGor2SJzTbLqqqz+oVzz4JXCHXOTJVS1EAOBvMOOZI9yQuK8ycTeGHd2KMQEUP7LxKMoxHP5AJsndFLv8A2zI7x4Q5RxnYCj9LlOOkSnCfR+kMDODYz6XtUyRYAQt2aIryYQOZfGYp58pC0ik5gpYkr+/vWGWmvv2xaQDnkqtcb+pStDRKVm6TMvXUoI3ox1BjM="
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  on:
    repo: peposso/xlsx2lua
    tags: true
  skip_cleanup: true
